### PR TITLE
Declare pnpm version in package.json

### PR DESCRIPTION
**Pull request by rotu**

### CODE REVIEW

**Comment by rotu** [comment]
@timsexperiments I'm puzzled by the publish workflow.

https://github.com/timsexperiments/es-exec/blob/e51af1747240015b6afee5be9860d71387e64830/.github/workflows/publish.yml

In particular:
1. Why do you install `pnpm` *before* setting up Node?
2. Why do you circumvent the version of node installed via setup node?
3. Why use `semver` at all? `pnpm version patch` and `npm version patch` already exist to bump the patch version.
  - Why install semver instead of including it in dev dependencies?

**Comment by timsexperiments** [comment]
TBH this publish workflow isn't ever used. I actually just made this late one night and haven't had time to look at it since. If you want to fix the publish script. I'd welcome the help as I don't imagine I am going to have the bandwidth to look at this again any time soon. I really just publish manually for now. It only takes a few minutes so it hasn't been a big enough issue for me to get a publish script working.

**Review by timsexperiments — APPROVED** [review]

**Comment by timsexperiments** [comment]
> @timsexperiments I'm puzzled by the publish workflow.
> 
> https://github.com/timsexperiments/es-exec/blob/e51af1747240015b6afee5be9860d71387e64830/.github/workflows/publish.yml
> 
> In particular:
> 
> 1. Why do you install `pnpm` _before_ setting up Node?
> 2. Why do you circumvent the version of node installed via setup node?
> 3. Why use `semver` at all? `pnpm version patch` and `npm version patch` already exist to bump the patch version.
> 
> * Why install semver instead of including it in dev dependencies?

TBH this publish workflow isn't ever used. I actually just made this late one night and haven't had time to look at it since. If you want to fix the publish script. I'd welcome the help as I don't imagine I am going to have the bandwidth to look at this again any time soon. I really just publish manually for now. It only takes a few minutes so it hasn't been a big enough issue for me to get a publish script working.

**Comment by timsexperiments** [comment]
@rotu Here is an [issue](https://github.com/timsexperiments/es-exec/issues/21) if you want to take this on.

**Pull request merged**
